package projeto_es2;


import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author vitor
 */
public class ItensMenu extends javax.swing.JPanel {

    
    private boolean selecionado;
    
    private boolean over;
    
    /**
     * Creates new form ItensMenu
     * @param data
     */
    public ItensMenu(ModeloMenu data) {
        initComponents();
        setOpaque(false);
        if(data.getTipo()== ModeloMenu.TipoMenu.MENU){
            LabelItemMenu.setText(data.getNomeCampo());
        }else if(data.getTipo() == ModeloMenu.TipoMenu.TYTLE){
            LabelItemMenu.setText(data.getNomeCampo());
        }else{
            LabelItemMenu.setText(" ");
        }
    }
    
    public void setSelecionado(boolean s){
        this.selecionado = s;
        repaint();
    }
    
    public void setOver(boolean over){
        this.over = over;
        repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g){
        if(selecionado || over){
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            if(selecionado){
                g2.setColor(new Color(225,225,225,80));
            }else{
                g2.setColor(new Color(225,225,225,80));
            }
            g2.fillRoundRect(10, 0, getWidth()-20, getHeight(), 15, 15);
        }
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelItemMenu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        LabelItemMenu.setBackground(new java.awt.Color(255, 255, 255));
        LabelItemMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelItemMenu.setForeground(new java.awt.Color(255, 255, 255));
        LabelItemMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelItemMenu.setText("ItemMenu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelItemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelItemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelItemMenu;
    // End of variables declaration//GEN-END:variables
}
