package projeto_es2;

import java.awt.Color;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author vitor
 */
public class TelaAgendarConsulta extends javax.swing.JPanel {

    MaskFormatter mfData;
    
    Pet P = new Pet();
    
    /**
     * Creates new form TelaAgendarConsulta
     */
    public TelaAgendarConsulta() {
        try {
            mfData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            System.out.println("Ocorreu um erro na criação da máscara!");
        }
        initComponents();
        ButtonMarcar.setBackground(Color.WHITE);
        ButtonVerD.setBackground(Color.WHITE);
        ButtonVerP.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextCpfDono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextNomePet = new javax.swing.JTextField();
        TextHorario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtonMarcar = new javax.swing.JButton();
        TextData = new javax.swing.JFormattedTextField(mfData);
        ButtonVerP = new javax.swing.JButton();
        ButtonVerD = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1018, 708));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("CPF do Proprietário:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nome do Pet:");

        TextNomePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomePetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Data da Consulta:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Horário da Consulta:");

        ButtonMarcar.setText("Marcar Consulta");
        ButtonMarcar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMarcarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMarcarMouseExited(evt);
            }
        });
        ButtonMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMarcarActionPerformed(evt);
            }
        });

        ButtonVerP.setText("Verificar Pet");
        ButtonVerP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonVerPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonVerPMouseExited(evt);
            }
        });
        ButtonVerP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerPActionPerformed(evt);
            }
        });

        ButtonVerD.setText("Verificar Data");
        ButtonVerD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonVerDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonVerDMouseExited(evt);
            }
        });
        ButtonVerD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonMarcar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonVerP)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextCpfDono, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextHorario)
                                    .addComponent(TextData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ButtonVerD))))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(TextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCpfDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(TextHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonVerP)
                    .addComponent(ButtonVerD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(ButtonMarcar)
                .addGap(158, 158, 158))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomePetActionPerformed

    private void ButtonMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMarcarActionPerformed
        // TODO add your handling code here:
        P.setNome(TextNomePet.getText());
        P.setCpfdono(TextCpfDono.getText());
                
        P.agendarConsulta(P, TextData.getText(), TextHorario.getText());
        
    }//GEN-LAST:event_ButtonMarcarActionPerformed

    private void ButtonMarcarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMarcarMouseEntered
        // TODO add your handling code here:
        ButtonMarcar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ButtonMarcarMouseEntered

    private void ButtonMarcarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMarcarMouseExited
        // TODO add your handling code here:
        ButtonMarcar.setBackground(Color.WHITE);
    }//GEN-LAST:event_ButtonMarcarMouseExited

    private void ButtonVerPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerPActionPerformed
        // TODO add your handling code here:
        if(P.petCadastrado(TextCpfDono.getText(), TextNomePet.getText())){
            JOptionPane.showMessageDialog(this, "Pet encontrado!");
        }else{
            JOptionPane.showMessageDialog(this, "Pet não encontrado!");
        }
    }//GEN-LAST:event_ButtonVerPActionPerformed

    private void ButtonVerDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerDActionPerformed
        // TODO add your handling code here:
        if(P.horarioDisponivel(TextData.getText(), TextHorario.getText())){
            JOptionPane.showMessageDialog(this, "Data disponivel!");
        }else{
            JOptionPane.showMessageDialog(this, "Data indisponivel");
        }
    }//GEN-LAST:event_ButtonVerDActionPerformed

    private void ButtonVerPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVerPMouseEntered
        // TODO add your handling code here:
        ButtonVerP.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ButtonVerPMouseEntered

    private void ButtonVerPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVerPMouseExited
        // TODO add your handling code here:
        ButtonVerP.setBackground(Color.WHITE);
    }//GEN-LAST:event_ButtonVerPMouseExited

    private void ButtonVerDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVerDMouseEntered
        // TODO add your handling code here:
        ButtonVerD.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ButtonVerDMouseEntered

    private void ButtonVerDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVerDMouseExited
        // TODO add your handling code here:
        ButtonVerD.setBackground(Color.WHITE);
    }//GEN-LAST:event_ButtonVerDMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMarcar;
    private javax.swing.JButton ButtonVerD;
    private javax.swing.JButton ButtonVerP;
    private javax.swing.JTextField TextCpfDono;
    private javax.swing.JFormattedTextField TextData;
    private javax.swing.JTextField TextHorario;
    private javax.swing.JTextField TextNomePet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
