/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_es2;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class TelaLogin extends javax.swing.JFrame {

    Funcionario F = new Funcionario();
    
    TelaRecuperarSenha RS = new TelaRecuperarSenha();
    
    Image icon = new ImageIcon(this.getClass().getResource("/logo.png.png")).getImage();
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        ButtonConfirmar.setBackground(Color.WHITE);
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonConfirmar = new javax.swing.JButton();
        TextLoginCPF = new javax.swing.JTextField();
        TextLoginSenha = new javax.swing.JPasswordField();
        TextButtonSenha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 226, 223));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 37, -1));

        jLabel1.setText("CPF:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 30, -1));

        ButtonConfirmar.setText("Confirmar");
        ButtonConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonConfirmarMouseExited(evt);
            }
        });
        ButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, -1));

        TextLoginCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLoginCPFActionPerformed(evt);
            }
        });
        getContentPane().add(TextLoginCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, -1));

        TextLoginSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLoginSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(TextLoginSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, -1));

        TextButtonSenha.setText("Esqueceu a senha?");
        TextButtonSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextButtonSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(TextButtonSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, 18));

        jPanel1.setBackground(new java.awt.Color(234, 226, 223));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Login");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_es2/Icons/pexels-sam-lion-5731874 (1)-PhotoRoom.png-PhotoRoom.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextLoginCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLoginCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLoginCPFActionPerformed

    private void TextLoginSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLoginSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLoginSenhaActionPerformed

    private void ButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmarActionPerformed
        // TODO add your handling code here:
        F.setCpf(TextLoginCPF.getText());
        F.setSenha(TextLoginSenha.getText());
        
        if(F.getCpf().equals(null)|| F.getSenha().equals(null)){
            JOptionPane.showMessageDialog(this, "Por Favor, Preencha todos os campos!");
            return;
        } 
        
        F.funcionarioLogin(F.getCpf(),F.getSenha());
        
        if(F.getFuncao() != null){
            TelaInicial TI = new TelaInicial(F.getFuncao(),F.getNome());
            TI.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "CPF ou Senha Incorretos!");
            return;
        }
    }//GEN-LAST:event_ButtonConfirmarActionPerformed

    private void TextButtonSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextButtonSenhaMouseClicked
        // TODO add your handling code here:
        RS.setVisible(true);
    }//GEN-LAST:event_TextButtonSenhaMouseClicked

    private void ButtonConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfirmarMouseEntered
        // TODO add your handling code here:
        ButtonConfirmar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ButtonConfirmarMouseEntered

    private void ButtonConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfirmarMouseExited
        // TODO add your handling code here:
        ButtonConfirmar.setBackground(Color.WHITE);
    }//GEN-LAST:event_ButtonConfirmarMouseExited
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfirmar;
    private javax.swing.JLabel TextButtonSenha;
    private javax.swing.JTextField TextLoginCPF;
    private javax.swing.JPasswordField TextLoginSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
