package projeto_es2;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author vitor
 */
public class TelaEstoqueMedicamentos extends javax.swing.JPanel {

    Medicamentos M = new Medicamentos();
    
    /**
     * Creates new form TelaEstoqueMedicamentos
     */
    public TelaEstoqueMedicamentos() {
        initComponents();
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        ButtonAdicionar.setBackground(Color.WHITE);
        ButtonEditar.setBackground(Color.WHITE);
        ButtonExcluir.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextMed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextQuant = new javax.swing.JTextField();
        ButtonAdicionar = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMedi = new projeto_es2.TableDsigne();

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nome do Medicamento:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Quantidade:");

        ButtonAdicionar.setText("Adicionar");
        ButtonAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonAdicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonAdicionarMouseExited(evt);
            }
        });
        ButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdicionarActionPerformed(evt);
            }
        });

        ButtonEditar.setText("Editar");
        ButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonEditarMouseExited(evt);
            }
        });
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButtonExcluir.setText("Excluir");
        ButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonExcluirMouseExited(evt);
            }
        });
        ButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirActionPerformed(evt);
            }
        });

        TableMedi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicamento", "Quantidade"
            }
        ));
        TableMedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMediMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMedi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextMed, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonExcluir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAdicionar)
                    .addComponent(ButtonEditar)
                    .addComponent(ButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdicionarActionPerformed
        // TODO add your handling code here:
        M.setNomemedicamento(TextMed.getText());
        M.setQuantidade(TextQuant.getText());
        
        if(M.getNomemedicamento().isEmpty() || M.getQuantidade().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por Favor, Preencha todos os campos!");
            return;
        }
        
        M.addMedicamento();
        
        DefaultTableModel tableMedi = (DefaultTableModel) TableMedi.getModel();
        
        Object[] newrow = {M.getNomemedicamento(),M.getQuantidade()};
        
        tableMedi.addRow(newrow);
        
        TextMed.setText("");
        TextQuant.setText("");
        JOptionPane.showMessageDialog(this, "Medicamento adicionado com sucesso!");
        
    }//GEN-LAST:event_ButtonAdicionarActionPerformed

    private void TableMediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMediMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            int linha = TableMedi.getSelectedRow();
            
            TextMed.setText((String)TableMedi.getValueAt(linha, 0));
            TextQuant.setText((String)TableMedi.getValueAt(linha, 1));
        }
    }//GEN-LAST:event_TableMediMouseClicked

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = TableMedi.getSelectedRow();
        
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Por Favor, Selecione uma Linha da Tabela!");
        }else{
            
            M.setNomemedicamento(TextMed.getText());
            M.setQuantidade(TextQuant.getText());
            
            if(M.getNomemedicamento().isEmpty() || M.getQuantidade().isEmpty()){
                JOptionPane.showMessageDialog(this, "Por Favor, Preencha todos os campos!");
                return;
        }
            
            M.updateNomemedicamento(M, M.getNomemedicamento());
            M.updateQtdmedicamento(M);
            
            setTableMedi(M.getNomemedicamento(),M.getQuantidade(),linhaSelecionada);
            
            TextMed.setText("");
            TextQuant.setText("");
            JOptionPane.showMessageDialog(this, "Medicamento editado com sucesso!");
        }
    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void ButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = TableMedi.getSelectedRow();
        
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Por Favor, Selecione uma Linha da Tabela!");
        }
        
        DefaultTableModel tableMedi = (DefaultTableModel) TableMedi.getModel();
        
        //CPF para busca no Banco de Dados
        M.setNomemedicamento((String)TableMedi.getValueAt(linhaSelecionada, 0));
        
        M.deleteMedicamento();
        
        //Remover as informações do funcionário selecionado da tabela
        
        tableMedi.removeRow(linhaSelecionada);
        
        TextMed.setText("");
        TextQuant.setText("");
        
        JOptionPane.showMessageDialog(this, "Medicamento excluido com sucesso!");
    }//GEN-LAST:event_ButtonExcluirActionPerformed

    private void ButtonAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAdicionarMouseEntered
        // TODO add your handling code here:
        ButtonAdicionar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ButtonAdicionarMouseEntered

    private void ButtonAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAdicionarMouseExited
        // TODO add your handling code here:
        ButtonAdicionar.setBackground(Color.WHITE);
    }//GEN-LAST:event_ButtonAdicionarMouseExited

    private void ButtonEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEditarMouseEntered
        // TODO add your handling code here:
        ButtonEditar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ButtonEditarMouseEntered

    private void ButtonEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEditarMouseExited
        // TODO add your handling code here:
        ButtonEditar.setBackground(Color.WHITE);
    }//GEN-LAST:event_ButtonEditarMouseExited

    private void ButtonExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExcluirMouseEntered
        // TODO add your handling code here:
        ButtonExcluir.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ButtonExcluirMouseEntered

    private void ButtonExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExcluirMouseExited
        // TODO add your handling code here:
        ButtonExcluir.setBackground(Color.WHITE);
    }//GEN-LAST:event_ButtonExcluirMouseExited

    public void setTableMedi(String nome, String quantidade, int linha){
        
        TableMedi.setValueAt(nome, linha, 0);
        TableMedi.setValueAt(quantidade, linha, 1);
    }
    
    public void SetTable(){
        M.readMedicamento();
        
        int i;
        int size = M.getSize();
        
        for(i = 0;i < size; i++){
            
            M.setMedicamento(i);
        
            DefaultTableModel tableMedi= (DefaultTableModel) TableMedi.getModel();
        
            Object[] newrow = {M.getNomemedicamento(),M.getQuantidade()};
        
            tableMedi.addRow(newrow);
        }
        
        M.clearList();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdicionar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonExcluir;
    private projeto_es2.TableDsigne TableMedi;
    private javax.swing.JTextField TextMed;
    private javax.swing.JTextField TextQuant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
